### ISSUE TITLE
check if it is possible to test porting BBS[Lua/Ruby] to dreambbs

### ISSUE THREAD

**Issue by holishing** [ccns/dreambbs#30]
and how many works we have to do for this.

**Comment by itscache** [comment]
How about having a quick view on M3-itoc-BBSRuby of NCKUEEBBS?

**Comment by holishing** [comment]
I'll consider that, too. :)

**Comment by holishing** [comment]
PR #34 is working on it

**Comment by holishing** [comment]
@IepIweidieng is working progress on this.  If there's related discussion, just open new issue again.
